[clog]
# A repository link with the trailing '.git' which will be used to generate
# all commit and issue links
repository = "https://github.com/xmas92/A-Rust-Project"
# A constant release title
subtitle = "A Rust Project"

# The preferred way to set a constant changelog. This file will be read for old changelog
# data, then prepended to for new changelog data. It's the equivilant to setting
# both infile and outfile to the same file.
#
# Do not use with outfile or infile fields!
#
# Defaults to stdout when omitted
changelog = "CHANGELOG.md"

# If you use tags, you can set the following if you wish to only pick
# up changes since your latest tag
from-latest-tag = true

[sections]
Feature = ["feat"]
Bugfix = ["fix"]
Documentation = ["docs"]
Test = ["test"]
Build = ["build"]
CI = ["ci"]
Performance = ["perf"]
Refactor = ["refactor"]
Style = ["style"]
Vendor = ["vendor"]
Chore = ["chore"]
Revert = ["revert"]
